In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
decitree = pd.read_csv('E:/May 30 DecisionTree/titanic_data.csv')

In [3]:
decitree.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
decitree.shape

(891, 12)

In [5]:
decitree.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
decitree['Age'].isnull().sum()

177

In [7]:
decitree['Age'].fillna(0, inplace=True)

In [8]:
decitree['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [9]:
decitree['Sex']=decitree.Sex.replace({'male':0, 'female':1})

In [10]:
decitree.drop(['Name'], axis=1, inplace=True)

In [11]:
decitree.drop(['Ticket'], axis=1, inplace = True)

In [12]:
decitree['Cabin'].isnull().sum()

687

In [13]:
decitree.drop(['Cabin'], axis=1, inplace=True)

In [14]:
decitree['Embarked'].fillna(0, inplace=True)

In [15]:
decitree['Embarked'].value_counts()

S    644
C    168
Q     77
0      2
Name: Embarked, dtype: int64

In [16]:
decitree['Embarked']=decitree.Embarked.replace({'S':1, 'C':2, 'Q':3 })

In [17]:
decitree.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [18]:
decitree.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked         int64
dtype: object

In [19]:
X = decitree[['PassengerId', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]
Y = decitree[['Survived']]

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 42)

In [21]:
X_train

PassengerId  Pclass  Sex    Age  SibSp  Parch      Fare  Embarked
298          299       1    0   0.00      0      0   30.5000         1
884          885       3    0  25.00      0      0    7.0500         1
247          248       2    1  24.00      0      2   14.5000         1
478          479       3    0  22.00      0      0    7.5208         1
305          306       1    0   0.92      1      2  151.5500         1
..           ...     ...  ...    ...    ...    ...       ...       ...
106          107       3    1  21.00      0      0    7.6500         1
270          271       1    0   0.00      0      0   31.0000         1
860          861       3    0  41.00      2      0   14.1083         1
435          436       1    1  14.00      1      2  120.0000         1
102          103       1    0  21.00      0      1   77.2875         1

[668 rows x 8 columns]

In [22]:
X_test

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
709          710       3    0   0.0      1      1  15.2458         2
439          440       2    0  31.0      0      0  10.5000         1
840          841       3    0  20.0      0      0   7.9250         1
720          721       2    1   6.0      0      1  33.0000         1
39            40       3    1  14.0      1      0  11.2417         2
..           ...     ...  ...   ...    ...    ...      ...       ...
880          881       2    1  25.0      0      1  26.0000         1
425          426       3    0   0.0      0      0   7.2500         1
101          102       3    0   0.0      0      0   7.8958         1
199          200       2    1  24.0      0      0  13.0000         1
424          425       3    0  18.0      1      1  20.2125         1

[223 rows x 8 columns]

In [23]:
Y_test

Survived
709         1
439         0
840         0
720         1
39          1
..        ...
880         1
425         0
101         0
199         0
424         0

[223 rows x 1 columns]

In [24]:
Y_train

Survived
298         1
884         0
247         1
478         0
305         1
..        ...
106         1
270         0
860         0
435         1
102         0

[668 rows x 1 columns]

In [25]:
from sklearn.decomposition import PCA

In [26]:
pca = PCA(n_components = 4)

In [27]:
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [28]:
from sklearn.tree import DecisionTreeClassifier

In [29]:
decisiontree = DecisionTreeClassifier()

In [30]:
#cross_val_score(clf, decisiontree, iris.target, cv=10)

In [31]:
decisiontree.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [32]:
y_pred = decisiontree.predict(X_train)
x_pred = decisiontree.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
print('Training accuracy score:', accuracy_score(y_pred, Y_train))
print('Testing accuracy score:', accuracy_score(x_pred, Y_test))

Training accuracy score: 1.0
Testing accuracy score: 0.6681614349775785


In [35]:
from sklearn.metrics import f1_score

In [36]:
print('Training f1 score:', f1_score(y_pred, Y_train))
print('Testing f1 score:', f1_score(x_pred, Y_test))

Training f1 score: 1.0
Testing f1 score: 0.5795454545454545


In [37]:
from sklearn.metrics import confusion_matrix

In [38]:
cm = confusion_matrix(x_pred, Y_test)

In [39]:
cm

array([[98, 38],
       [36, 51]], dtype=int64)

In [40]:
from sklearn.metrics import roc_curve, auc

In [41]:
false_positive_rate, true_positive_rate, thresholds = roc_curve(x_pred, Y_test)
roc_auc = auc(false_positive_rate, true_positive_rate)

In [42]:
roc_auc

0.6533975659229209

In [43]:
from sklearn.model_selection import GridSearchCV

In [44]:
model1 = DecisionTreeClassifier(criterion="entropy", max_depth=12)

In [45]:
#parameters = {'max_depth':[2,4,6,8,10],'min_samples_leaf':[2,4,6,8,10], 'min_samples_split':[2,4,6,8,10]}

parameters = {'max_depth' : [1, 32, 32], 'min_samples_leaf':[0.1, 0.5, 5], 'min_samples_split':[0.1, 1.0, 10]}

#parameter tuning

In [46]:
grid_obj = GridSearchCV(model1, parameters, scoring=None)

In [47]:
dt_gs = grid_obj.fit(X_test, Y_test)

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [48]:
loop = grid_obj.best_estimator_

In [49]:
loop.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=32,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=0.1, min_samples_split=0.1,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [50]:
besttrain = loop.predict(X_train)
besttest = loop.predict(X_test)

In [51]:
print('Training F1 score:', f1_score(besttrain, Y_train))
print('Testing F1 score:', f1_score(besttest, Y_test))
print('Training accuracy:', accuracy_score(besttrain, Y_train))
print('Testing accuracy:', accuracy_score(besttest, Y_test))

Training F1 score: 0.5306122448979592
Testing F1 score: 0.4785276073619632
Training accuracy: 0.6901197604790419
Testing accuracy: 0.6188340807174888


In [52]:
cm = confusion_matrix(besttest, Y_test)
cm

array([[99, 50],
       [35, 39]], dtype=int64)

In [53]:
false_positive_rate, true_positive_rate, thresholds = roc_curve(besttest, Y_test)
roc_auc = auc(false_positive_rate, true_positive_rate)

In [54]:
roc_auc

0.5957282786141846

In [55]:
from sklearn.ensemble import RandomForestClassifier

In [56]:
#type of approches
#classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)

classifier = RandomForestClassifier()

In [57]:
param_dist = {"max_depth": [3, None],
              "n_estimators": list(range(10, 200)),
              "max_features": list(range(1, X_test.shape[1]+1)),
              "min_samples_split": list(range(2, 11)),
              "min_samples_leaf": list(range(1, 11)),
              "bootstrap": [True, False],
              "criterion": ["gini", "entropy"]}

In [58]:
classifier.fit(X_train, Y_train)

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [59]:
bestmodel_train = classifier.predict(X_train)
bestmodel_test = classifier.predict(X_test)

In [60]:
print('training f1 score:', f1_score(bestmodel_train, Y_train))
print('testing f1 score:', f1_score(bestmodel_test, Y_test))
print('training accuracy score:', accuracy_score(bestmodel_train, Y_train))
print('testing accuracy score:', accuracy_score(bestmodel_test, Y_test))

training f1 score: 0.9880478087649401
testing f1 score: 0.5605095541401274
training accuracy score: 0.9910179640718563
testing accuracy score: 0.6905829596412556


In [61]:
cm = confusion_matrix(bestmodel_test, Y_test)
cm

array([[110,  45],
       [ 24,  44]], dtype=int64)

In [62]:
false_positive_rate, true_positive_rate, thresholds = roc_curve(bestmodel_test, Y_test)
roc_auc = auc(false_positive_rate, true_positive_rate)

In [63]:
roc_auc

0.6783681214421253

In [96]:
from sklearn.ensemble import AdaBoostClassifier

In [101]:
#Boost = AdaBoostClassifier()
#Boost = AdaBoostClassifier(n_estimators=300, learning_rate=0.2)
Boost = AdaBoostClassifier(n_estimators=100, random_state= 42)

In [102]:
boost = ada_mod.fit(X_train, Y_train)

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [103]:
ypred = boost.predict(X_train)
xpred = boost.predict(X_test)

In [104]:
print('training F1 score:', f1_score(ypred, Y_train))
print('testing F1 score:', f1_score(xpred, Y_test))
print('training accuracy:', accuracy_score(ypred, Y_train))
print('testing accuracy:', accuracy_score(xpred, Y_test))

training F1 score: 0.6638655462184874
testing F1 score: 0.5868263473053893
training accuracy: 0.7604790419161677
testing accuracy: 0.6905829596412556


In [105]:
cm = confusion_matrix(xpred, Y_test)
cm

array([[105,  40],
       [ 29,  49]], dtype=int64)

In [106]:
false_positive_rate, true_positive_rate, thresholds = roc_curve(xpred, Y_test)
roc_auc = auc(false_positive_rate, true_positive_rate)

In [107]:
roc_auc

0.6761715296198055